# Generated by Django 3.1.3 on 2020-11-16 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('privilege', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='garderie.user')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('mail', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorairesDePresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrivee', models.DateTimeField(verbose_name="Heure d'arrivée")),
                ('depart', models.DateTimeField(verbose_name='Heure de départ')),
                ('prevu', models.BooleanField()),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garderie.enfant')),
            ],
        ),
        migrations.AddField(
            model_name='enfant',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garderie.parent'),
        ),
    ]
