# Generated by Django 3.1.3 on 2021-01-31 18:18

from django.db import migrations, models
import django.db.models.deletion
import garderie.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse mail')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Nom')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', garderie.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=1, verbose_name='Mois')),
                ('year', models.IntegerField(choices=[(2000, 'Y'), (2001, 'Y'), (2002, 'Y'), (2003, 'Y'), (2004, 'Y'), (2005, 'Y'), (2006, 'Y'), (2007, 'Y'), (2008, 'Y'), (2009, 'Y'), (2010, 'Y'), (2011, 'Y'), (2012, 'Y'), (2013, 'Y'), (2014, 'Y'), (2015, 'Y'), (2016, 'Y'), (2017, 'Y'), (2018, 'Y'), (2019, 'Y'), (2020, 'Y'), (2021, 'Y')], default=2021, verbose_name='Année')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Taux à la demi-heure (en €)')),
                ('date_start', models.DateTimeField(verbose_name='Date de départ')),
                ('date_end', models.DateTimeField(null=True, verbose_name='Date de fin')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='garderie.user')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Téléphone')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateTimeField(verbose_name="Heure d'arrivée")),
                ('departure', models.DateTimeField(null=True, verbose_name='Heure de départ')),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='garderie.bill')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garderie.child', verbose_name='Enfant')),
                ('rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='garderie.hourlyrate')),
            ],
        ),
        migrations.CreateModel(
            name='ReliablePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Téléphone')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garderie.child', verbose_name='Enfant concerné')),
            ],
        ),
        migrations.CreateModel(
            name='ExpectedPresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], default=6, verbose_name='Jour')),
                ('period', models.IntegerField(choices=[(0, 'Matin'), (1, 'Soir')], default='Matin', verbose_name='Heure de présence')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garderie.child', verbose_name='Enfant associé')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garderie.child', verbose_name='Enfant associé'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_set', to='garderie.parent'),
        ),
        migrations.AddField(
            model_name='child',
            name='second_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_set2', to='garderie.parent'),
        ),
    ]
