# Generated by Django 3.1.3 on 2021-01-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garderie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='amount',
        ),
        migrations.AlterField(
            model_name='reliableperson',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
    ]
