# Generated by Django 3.1.3 on 2021-01-27 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garderie', '0002_auto_20210125_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reliableperson',
            name='parent',
        ),
        migrations.AddField(
            model_name='reliableperson',
            name='child',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='garderie.child'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expectedpresence',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=2, verbose_name='Jour'),
        ),
        migrations.AlterField(
            model_name='hourlyrate',
            name='value',
            field=models.FloatField(verbose_name='Taux à la demi-heure (en €)'),
        ),
    ]
