# Generated by Django 3.1.3 on 2021-02-01 01:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('garderie', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='month',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=2, verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='expectedpresence',
            name='day',
            field=models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], default=0, verbose_name='Jour'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, null=True, region=None, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='reliableperson',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, null=True, region=None, verbose_name='Téléphone'),
        ),
    ]
