# Generated by Django 3.1.3 on 2021-02-02 01:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('garderie', '0003_auto_20210201_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_message', models.TextField(verbose_name='En-tête des factures')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Téléphone')),
                ('address', models.CharField(max_length=100, verbose_name='Adresse de la garderie')),
            ],
        ),
        migrations.AlterField(
            model_name='expectedpresence',
            name='day',
            field=models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], default=1, verbose_name='Jour'),
        ),
    ]
