# Generated by Django 3.1.3 on 2021-02-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garderie', '0004_auto_20210202_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Nom de la garderie'),
            preserve_default=False,
        ),
    ]
