# Generated by Django 3.1.3 on 2020-11-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garderie', '0005_auto_20201120_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='user',
            new_name='uid',
        ),
    ]
