# Generated by Django 3.1.3 on 2021-02-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garderie', '0005_config_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='email_reset',
            field=models.TextField(default='', verbose_name='Email de réinitialisation de mot de passe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='email_welcome',
            field=models.TextField(default='', verbose_name='Email de bienvenue'),
            preserve_default=False,
        ),
    ]
