# Generated by Django 3.1.3 on 2021-02-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garderie', '0006_auto_20210202_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='mail',
            field=models.EmailField(default='', max_length=254, verbose_name='Email de contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expectedpresence',
            name='day',
            field=models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], default=2, verbose_name='Jour'),
        ),
    ]
