# Generated by Django 3.1.3 on 2021-02-03 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garderie', '0007_auto_20210203_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='parent',
            field=models.ForeignKey(default=48, on_delete=django.db.models.deletion.DO_NOTHING, to='garderie.parent', verbose_name='Facture'),
            preserve_default=False,
        ),
    ]
