# Generated by Django 3.1.3 on 2020-12-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garderie', '0011_auto_20201219_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='departure',
            field=models.DateTimeField(null=True, verbose_name='Heure de départ'),
        ),
    ]
