# Generated by Django 3.1.3 on 2021-01-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garderie', '0013_auto_20210105_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='rate',
        ),
    ]
