# Generated by Django 3.1.3 on 2021-01-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garderie', '0014_remove_bill_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='paid',
        ),
    ]
