# Generated by Django 3.1.3 on 2021-01-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garderie', '0016_auto_20210108_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='date_start',
        ),
        migrations.AddField(
            model_name='bill',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
        ),
        migrations.AddField(
            model_name='bill',
            name='year',
            field=models.IntegerField(choices=[(2000, 'Y'), (2001, 'Y'), (2002, 'Y'), (2003, 'Y'), (2004, 'Y'), (2005, 'Y'), (2006, 'Y'), (2007, 'Y'), (2008, 'Y'), (2009, 'Y'), (2010, 'Y'), (2011, 'Y'), (2012, 'Y'), (2013, 'Y'), (2014, 'Y'), (2015, 'Y'), (2016, 'Y'), (2017, 'Y'), (2018, 'Y'), (2019, 'Y'), (2020, 'Y'), (2021, 'Y')], default=2021),
        ),
        migrations.AddField(
            model_name='schedule',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='garderie.bill'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garderie.parent'),
        ),
    ]
