# Generated by Django 3.1.3 on 2021-01-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garderie', '0017_auto_20210114_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='expected',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='recurring',
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Montant total'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garderie.child', verbose_name='Enfant associé'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='year',
            field=models.IntegerField(choices=[(2000, 'Y'), (2001, 'Y'), (2002, 'Y'), (2003, 'Y'), (2004, 'Y'), (2005, 'Y'), (2006, 'Y'), (2007, 'Y'), (2008, 'Y'), (2009, 'Y'), (2010, 'Y'), (2011, 'Y'), (2012, 'Y'), (2013, 'Y'), (2014, 'Y'), (2015, 'Y'), (2016, 'Y'), (2017, 'Y'), (2018, 'Y'), (2019, 'Y'), (2020, 'Y'), (2021, 'Y')], default=2021, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='hourlyrate',
            name='value',
            field=models.FloatField(verbose_name='Taux horaire'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='reliableperson',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Préom'),
        ),
        migrations.AlterField(
            model_name='reliableperson',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='reliableperson',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garderie.child', verbose_name='Enfant'),
        ),
        migrations.CreateModel(
            name='ExpectedPresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=5, verbose_name='Jour')),
                ('period', models.IntegerField(choices=[(0, 'Matin'), (1, 'Soir')], default='Matin', verbose_name='Heure de présence')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garderie.child', verbose_name='Enfant associé')),
            ],
        ),
    ]
